import { StyleSheet } from 'react-native'
import { Colors } from '../../config/theme'
import { scale, verticalScale, moderateScale } from '../../utils/scaling'

export default StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: Colors.bgBlack,
  },
  headerContainer: {
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(8),
    borderBottomWidth: 1,
    borderBottomColor: '#00ACB34D',
    paddingBottom: verticalScale(12),
    alignItems: 'flex-start',
  },
  logoImage: {
    width: scale(120),
    height: verticalScale(35),
  },
  contentHeader: {
    paddingLeft: scale(22),
    marginTop: verticalScale(8),
    marginBottom: verticalScale(4),
  },
  screenTitle: {
    color: Colors.textPrimary,
    height: verticalScale(36),
  },
  tabOuterContainer: {
    paddingHorizontal: scale(22),
    marginBottom: verticalScale(8),
    width: '100%',
  },
  tabWrapper: {
    flexDirection: 'row',
    backgroundColor: Colors.bgSurface,
    borderRadius: moderateScale(8),
    padding: scale(2),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    width: '100%',
    height: verticalScale(35),
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: moderateScale(8),
  },
  tabButtonActive: {
    backgroundColor: '#00ACB3',
  },
  searchWrapper: {
    paddingHorizontal: scale(22),
    marginBottom: verticalScale(8),
  },
  searchInput: {
    backgroundColor: '#302e2e',
    borderRadius: moderateScale(8),
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(10),
    color: Colors.textPrimary,
    borderWidth: 1,
    borderColor: '#00ACB34D',
    width: '100%',
  },
  listContent: {
    paddingHorizontal: scale(22),
    paddingBottom: verticalScale(24),
  },
  cardContainer: {
    backgroundColor: Colors.bgSurface,
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    padding: scale(16),
    marginBottom: verticalScale(16),
  },
  mediaPlaceholder: {
    width: '100%',
    height: verticalScale(110),
    backgroundColor: Colors.textPrimary,
    borderRadius: moderateScale(12),
    marginBottom: verticalScale(16),
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  avatarGradient: {
    width: scale(56),
    height: scale(56),
    borderRadius: moderateScale(28),
  },
  profileNameContainer: {
    marginLeft: scale(12),
  },
  bioText: {
    color: Colors.textPrimary,
    marginBottom: verticalScale(12),
  },
  locationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(16),
  },
  websiteLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  linkIcon: {
    marginLeft: scale(4),
  },
  metricsContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.bgBlack,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    paddingVertical: verticalScale(12),
    marginBottom: verticalScale(12),
  },
  metricBox: {
    flex: 1,
    alignItems: 'center',
  },
  pricingStrip: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#302e2e',
    borderRadius: moderateScale(8),
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(12),
    marginBottom: verticalScale(12),
  },
  actionGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalScale(8),
  },
  actionButton: {
    flex: 0.48,
    backgroundColor: '#00ACB3',
    borderRadius: moderateScale(8),
    paddingVertical: verticalScale(10),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  dropdownIcon: {
    marginLeft: scale(4),
  },
  headerGradient: {
    width: scale(402),
    height: verticalScale(58),
    paddingTop: verticalScale(16),
    paddingRight: scale(150),
    paddingBottom: verticalScale(12),
    paddingLeft: scale(13),
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    marginRight: scale(16),
  },
  headerTitle: {
    color: Colors.textPrimary,
  },
  scrollContent: {
    paddingHorizontal: scale(22),
    paddingBottom: verticalScale(32),
  },
  mediaRectangle: {
    width: '100%',
    height: verticalScale(110),
    backgroundColor: Colors.textPrimary,
    borderRadius: moderateScale(16),
    marginTop: verticalScale(16),
    marginBottom: verticalScale(16),
  },
  profileMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  nameWrapper: {
    marginLeft: scale(12),
  },
  linkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statsDashboardContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.bgSurface,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    paddingVertical: verticalScale(12),
    marginBottom: verticalScale(16),
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
  },
  primaryActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: verticalScale(35),
    marginTop: verticalScale(16),
    marginBottom: verticalScale(20),
  },
  actionBtnLeft: {
    flex: 0.48,
    height: '100%',
  },
  actionBtnRight: {
    flex: 0.48,
    height: '100%',
  },
  gradientBtnBg: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: '#00ACB34D',
  },
  btnIconSpace: {
    marginRight: scale(4),
  },
  segmentedTabContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.bgBlack,
    borderRadius: moderateScale(8),
    padding: scale(2),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    width: '100%',
    height: verticalScale(35),
    marginBottom: verticalScale(20),
  },
  segmentButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: moderateScale(6),
  },
  segmentButtonActive: {
    backgroundColor: Colors.teal,
  },
  socialGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalScale(12),
  },
  socialPlatformCardCustomBorder: {
    flex: 0.48,
    backgroundColor: Colors.bgCard,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    padding: scale(12),
  },
  socialTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  socialHandleText: {
    marginLeft: scale(6),
    color: Colors.textSecondary,
  },
  socialMetricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  socialMetricElement: {
    alignItems: 'flex-start',
  },
  growthChartContainerCustomBorder: {
    backgroundColor: Colors.bgCard,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    padding: scale(16),
    marginTop: verticalScale(8),
    marginBottom: verticalScale(16),
  },
  chartHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(16),
  },
  dropdownSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.cyan,
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(4),
    borderRadius: moderateScale(6),
  },
  dropdownArrow: {
    marginLeft: scale(4),
  },
  mockChartVisualArea: {
    width: '100%',
    height: verticalScale(100),
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: Colors.borderStrong,
  },
  metaBlockSectionCustomBorder: {
    backgroundColor: Colors.bgBlack,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: '#00ACB34D',
    padding: scale(16),
    marginBottom: verticalScale(16),
  },
  sectionBlockHeading: {
    color: Colors.textPrimary,
    marginBottom: verticalScale(12),
  },
  badgeWrapRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scale(8),
  },
  pillBadgeContainerCustomBorder: {
    borderWidth: 1,
    borderColor: '#00ACB34D',
    borderRadius: moderateScale(8),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(6),
    backgroundColor: Colors.bgSurface,
  },
  contentGridSystem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: verticalScale(16),
  },
  contentColumnItem: {
    flex: 0.31,
    alignItems: 'center',
  },
  contentCardMediaFrame: {
    width: '100%',
    height: verticalScale(180),
    borderRadius: moderateScale(12),
    overflow: 'hidden',
    backgroundColor: Colors.bgSurface,
  },
  contentCardImageRadius: {
    borderRadius: moderateScale(12),
  },
  contentCardDimmingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'flex-end',
    padding: scale(6),
  },
  contentOverlaySubtitleText: {
    color: Colors.textPrimary,
    fontSize: moderateScale(9),
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: moderateScale(12),
  },
  contentMediaActionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
    height: verticalScale(30),
    marginTop: verticalScale(12),
    borderWidth: 1,
    borderColor: '#DD21E3',
    borderRadius: moderateScale(6),
    paddingTop: verticalScale(5),
    paddingBottom: verticalScale(5),
    paddingHorizontal: scale(10),
    backgroundColor: Colors.bgBlack,
    opacity: 0.8,
  },
  contentFooterActionLabel: {
    color: Colors.textPrimary,
    fontSize: moderateScale(10),
    fontWeight: '700',
  },
  pricingHeaderLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pricingDescriptionText: {
    color: Colors.textSecondary,
    fontSize: moderateScale(11),
    lineHeight: moderateScale(15),
    marginTop: verticalScale(6),
  },
  // Append these keys cleanly to your existing StyleSheet object layout:
  pricingDeckContainer: {
    width: '100%',
  },
  platformAccordionWrapper: {
    marginBottom: verticalScale(10),
    borderRadius: moderateScale(10),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#00ACB366',
    backgroundColor: '#302e2e',
  },
  accordionHeaderButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(14),
    backgroundColor: '#302e2e',
  },
  accordionLeftSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  platformHeaderIcon: {
    marginRight: scale(12),
  },
  platformHeaderText: {
    color: Colors.textPrimary,
    fontWeight: '500',
  },
  accordionContentDropdown: {
    paddingHorizontal: scale(12),
    paddingBottom: verticalScale(12),
    backgroundColor: Colors.bgCard,
  },
  pricingTierCardCustomBorder: {
    backgroundColor: Colors.bgSurface,
    borderWidth: 1,
    borderColor: '#2C2C2E',
    borderRadius: moderateScale(8),
    padding: scale(14),
    marginTop: verticalScale(8),
  },
  sectionTitleQuote: {
    color: Colors.textPrimary,
    marginTop: verticalScale(20),
    marginBottom: verticalScale(10),
  },
  quotePlatformRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(14),
    backgroundColor: '#302e2e',
    borderWidth: 1,
    borderColor: '#1C1C1E',
    borderRadius: moderateScale(10),
    marginBottom: verticalScale(10),
  },
  quoteDropdownList: {
    backgroundColor: '#302e2e',
    borderWidth: 1,
    borderColor: '#1C1C1E',
    borderRadius: moderateScale(10),
    marginBottom: verticalScale(10),
    overflow: 'hidden',
  },
  quoteDropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(12),
  },
  quoteDropdownItemActive: {
    backgroundColor: 'rgba(0, 185, 192, 0.1)',
  },
  servicesDropdownHeader: {
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(10),
    borderBottomWidth: 1,
    borderBottomColor: '#1C1C1E',
  },
  checkboxOuter: {
    width: scale(20),
    height: scale(20),
    borderRadius: moderateScale(4),
    borderWidth: 2,
    borderColor: Colors.textDim,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(12),
  },
  checkboxOuterActive: {
    backgroundColor: Colors.teal,
    borderColor: Colors.teal,
  },
  radioButtonOuter: {
    width: scale(20),
    height: scale(20),
    borderRadius: moderateScale(10),
    borderWidth: 2,
    borderColor: Colors.textDim,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonOuterActive: {
    borderColor: Colors.teal,
  },
  radioButtonInner: {
    width: scale(10),
    height: scale(10),
    borderRadius: moderateScale(5),
    backgroundColor: Colors.teal,
  },
  quotePlaceholderBox: {
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: moderateScale(10),
    padding: scale(16),
    minHeight: verticalScale(80),
    justifyContent: 'center',
  },
  estimatedCostCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: Colors.teal,
    borderRadius: moderateScale(10),
    padding: scale(16),
    marginTop: verticalScale(20),
  },
  estimatedCostSubtext: {
    color: Colors.cyan,
    fontSize: moderateScale(11),
    lineHeight: moderateScale(15),
    maxWidth: '80%',
    marginTop: verticalScale(4),
  },
  quoteInput: {
    backgroundColor: '#302e2e',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: moderateScale(10),
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(12),
    color: Colors.textPrimary,
    fontSize: moderateScale(14),
  },
  quoteTextArea: {
    minHeight: verticalScale(100),
    textAlignVertical: 'top',
  },
  dropdownSelectorQuote: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#302e2e',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: moderateScale(10),
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(14),
  },
  infoWorkflowCard: {
    flexDirection: 'row',
    backgroundColor: '#302e2e',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: moderateScale(12),
    padding: scale(16),
    marginTop: verticalScale(24),
    alignItems: 'center',
  },
  infoWorkflowTextContent: {
    flex: 1,
    paddingRight: scale(8),
  },
  workflowBullet: {
    color: Colors.textSecondary,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    marginBottom: verticalScale(4),
  },
  workflowImagePlaceholder: {
    width: scale(65),
    height: verticalScale(90),
    backgroundColor: '#b6d82c',
    borderRadius: moderateScale(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  workflowImage: {
    width: '100%',
    height: '100%',
  },
  submitQuoteBtn: {
    width: '100%',
    height: verticalScale(45),
    marginTop: verticalScale(24),
    marginBottom: verticalScale(16),
  },
  submitGradient: {
    flex: 1,
    borderRadius: moderateScale(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
})