packages:
  - 'packages/*'
minimumReleaseAge: 10080
onlyBuiltDependencies:
  - react-native-reanimated
  - react-native
  - react-native-worklets
  - core-js
  - esbuild
  - msgpackr-extract
  - lmdb

